version: "3.9"
services:
  db:
    image: mysql
    restart: always
    env_file:
      - /src/main/resources/.env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:root}
#      MYSQL_DATABASE: ${MYSQL_DATABASE:jwt_auth_db}
#      MYSQL_USER: ${MYSQL_USER:root}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD:root}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  spring-boot-jwt-app:
    build: .
    #restart: on-failure
    env_file:
      - /src/main/resources/.env
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:jwt_auth_db}?useSSL=false
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:root}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:root}
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db-data:
